# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

#pool:
#  name: Default
#  demands:
#    - kush-dev -equals True
    
#steps:
  
#- script: python diskSize.py 
#  workingDirectory: C:\Users\kvatsa\Desktop\git_hub\hello

jobs:
  - job: Windows
    pool: 
      name: Default
      demands: 
        - kush-dev -equals True
      steps:
      - script: echo hello from kush-dev
        displayName: cmd_task
  

  
#- script: echo Hello, world,yo! 
#  displayName: 'Run a one-line script'


#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
