# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
  demands:
    - kush-dev -equals True


  
  
  
steps:
- script: echo Hello, world,yo! 
  displayName: 'Run a one-line script'
  
-script: echo yo yo ma!
  working Directory: C:\Users\kvatsa\Desktop

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
